### ISSUE TITLE
Creating .sigs from custom libraries/jar files or exclude package hierarchies 

### ISSUE THREAD

**Issue by dazzleworth** [pnfsoftware/jeb2-androsig#2]
I checked out your signature generator for and it seems that I am unable to create libraries using jar files that i have already compiled. Or instead of the whole APK/dex I cant specify that I only want a single hierarchy within the APK/DEX file. I note that this was possible in JEB 1.X (see 2nd point)

> 2- The plugin asks the user for two pieces of information:
> 
> 

- The library name: it is recommended to use the format “<libraryname>-<version>”. Here, we will go for: android-support-13

> 

- **The regular expression that identifies which methods should be signed. We want to sign all methods of the android.support.v4 package, so we will input: Landroid/support/v4/.* (Java internal name convention)**

https://www.pnfsoftware.com/blog/jeb-1-3-how-to-sign-and-match-third-party-library-code/

**Comment by Fly13DW** [comment]
Thank you for your suggestion.
It has been implemented from version 1.1.4.
See implementation here: https://github.com/pnfsoftware/jeb2-androsig/commit/a163d51cf41a4a0c429495d5db370aaf179e5cae

Release version is available here: https://github.com/pnfsoftware/jeb2-androsig/tree/master/out
You can put the jar file in the coreplugins folder.

Regards

**Comment by dazzleworth** [comment]
Thanks for the update. Just curious, the previous update generated 2 files in the coreplugins folder one with .idx and .sig extentions. Now just .sig

What are these extentions for hope you can explain.

**Comment by Fly13DW** [comment]
Hello,

Sorry for late answer.
Sig file is generated when creating lib, this is "the one".
Idx is a binary temporary file (kept as cache) used to navigate through the Sig file much faster. It has been introduced due to marge sig files, keeping lots of different versions for each lib. It is dynamically created at first matching attempt and can be removed safely if you do not perform matching after.
